Test/Models/ContestModels/ContestSubmission.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace Test.Models
{
	public class ContestSubmission
	{
		public ContestSubmission()
		{
			Time = "0 ms";
			Memory = "0 KB";
		}


		[Key]
		public int Id { get; set; }

		public Contest Contest { get; set; }

		public int ContestId { get; set; }

		public Problem Problem { set; get; }

		[Required]
		public int ProblemId { get; set; }

		public string SubmissionId { get; set; }

		public ApplicationUser ApplicationUser { get; set; }

		[Required]
		public string ApplicationUserId { get; set; }

		public Language Language { get; set; }

		public int LanguageId { get; set; }

		public DateTime SubmissionTime { get; set; }

		[MaxLength(100)]
		public string Result { get; set; }

		public string Time { get; set; }

		public string Memory { get; set; }

		[Required]
		[AllowHtml]
		public string Code { get; set; }

		public static async Task<ContestSubmission> ProcessSubmissionAsync(ContestSubmission contestSubmission, Problem problem, Language language)
		{
			contestSubmission = (problem.SourceWebsite.Name == Problem.LocalProblem)
				? await SubmitLocalProblem(contestSubmission, problem, language)
				: await SubmitCodeForcesProblem(contestSubmission, problem, language);

			contestSubmission.SubmissionTime = DateTime.Now;
			return contestSubmission;
		}

		private static async Task<ContestSubmission> SubmitLocalProblem(ContestSubmission contestSubmission, Problem problem, Language language)
		{
			contestSubmission.Result = await LocalProblemApi.SubmitAsync(new
			{
				code = contestSubmission.Code,
				input = problem.SimJudgeDetails.TestCaseInput,
				output = problem.SimJudgeDetails.TestCaseOutput,
				language = language.Value
			});
			return contestSubmission;
		}

		private static async Task<ContestSubmission> SubmitCodeForcesProblem(ContestSubmission contestSubmission, Problem problem, Language language)
		{
			string contest_id = Problem.GetContestIdFromProblemId(problem.SourceProblemId);

			string submission_id = await CodeForcesProblemApi.SubmitAsync(new
			{
				problem_id = problem.SourceProblemId,
				code = contestSubmission.Code,
				language_id = language.Value
			});

			if (submission_id == "Duplicate")
			{
				contestSubmission.Result = "Duplicate Code on Source";
			}
			else
			{
				contestSubmission.SubmissionId = submission_id;

				var dataObject = new
				{
					submission_id,
					contest_id
				};
				contestSubmission.Result = await CodeForcesProblemApi.GetVerdictAsync(dataObject);
				contestSubmission.Time = await CodeForcesProblemApi.GetTimeAsync(dataObject);
				contestSubmission.Memory = await CodeForcesProblemApi.GetMemoryAsync(dataObject);
			}
			return contestSubmission;
		}
	}
}

Test/ViewModels/ContestViewModels/ContestSubmissionViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Test.Models;

namespace Test.ViewModels
{
	public class ContestSubmissionViewModel
	{
		public IEnumerable<Language> Languages { get; set; }

		public int? SubmissionId { get; set; }

		public string ProblemName { get; set; }

		public string SourceProblemId { get; set; }

		[Required]
		public int ProblemId { get; set; }

		[Required]
		public int ProblemDetailsId { get; set; }

		[Required]
		public string ApplicationUserId { get; set; }

		public int ContestId { get; set; }

		[Required]
		public int LanguageId { get; set; }

		public DateTime SubmissionTime { get; set; }

		[MaxLength(100)]
		public string Result { get; set; }

		public string Time { get; set; }

		public string Memory { get; set; }

		[Required]
		public string Code { get; set; }
	}
}

Test/ViewModels/ContestViewModels/ContestSubmissionsViewModel.cs
using System.Collections.Generic;
using Test.Models;

namespace Test.ViewModels
{
	public class ContestSubmissionsViewModel
	{
		public IEnumerable<ContestSubmission> ContestSubmissions { get; set; }

		public string ContestName { get; set; }
	}
}

Test/Controllers/Contests/ContestSubmissionsController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using Test.Models;
using Test.ViewModels;

namespace Test.Controllers
{
	public class ContestSubmissionsController : Controller
	{
		private ApplicationDbContext _context;

		public ContestSubmissionsController()
		{
			_context = new ApplicationDbContext();
		}


		protected override void Dispose(bool disposing)
		{
			_context.Dispose();
		}

		[Route("Contest/{id}/Submissions")]
		public ActionResult ViewSubmissions(int id)
		{
			var contest = _context.Contests.SingleOrDefault(c => c.Id == id);
			if (contest.StartDate > DateTime.Now)
			{
				return RedirectToAction("Index", "Contests");
			}
			var contestSubmissions = _context.ContestSubmissions
				.Where(s => s.ContestId == id)
				.Include(s => s.Contest)
				.Include(s => s.Problem)
				.Include(s => s.ApplicationUser)
				.Include(s => s.Language)
				.ToList();

			var contestSubmissionsViewModel = new ContestSubmissionsViewModel
			{
				ContestSubmissions = contestSubmissions,
				ContestName = contest.Name,
			};
			return View(contestSubmissionsViewModel);
		}

		[Route("Contest/{contestId}/Submission/{id}")]
		public ActionResult SubmissionDetails(int id, int contestId)
		{
			var submission = _context.ContestSubmissions
				.Include(s => s.Problem)
				.Include(s => s.ApplicationUser)
				.Include(s => s.Language)
				.SingleOrDefault(s => s.Id == id);

			if (submission == null)
				return HttpNotFound();

			return View(submission);
		}

		[Route("Contest/{contestId}/Submit/{Id}")]
		public ActionResult Submit(int id, int contestId)
		{
			var contest = _context.Contests.Single(c => c.Id == contestId);
			if (contest.StartDate > DateTime.Now)
			{
				return RedirectToAction("Index", "Contests");
			}
			var problem = _context.Problems
				.Include(p => p.SourceWebsite)
				.Include(p => p.CodeForcesDetails)
				.Include(p => p.SimJudgeDetails)
				.SingleOrDefault(p => p.Id == id);

			if (problem == null)
				return HttpNotFound();

			var userId = User.Identity.GetUserId();
			
			var languages = _context.Languages
				.Where(l => l.SourceWebsiteId == problem.SourceWebsiteId)
				.ToList();

			var submissionsViewModel = new ContestSubmissionViewModel()
			{
				Languages = languages,
				ApplicationUserId = userId,
				ProblemId = problem.Id,
				ProblemName = problem.Name,
				SourceProblemId = problem.SourceWebsite.Name + "-" + problem.SourceProblemId,
				ContestId = contestId
			};
			return View(submissionsViewModel);
		}

		[ValidateAntiForgeryToken]
		[HttpPost]
		public async Task<ActionResult> SaveSubmissionAsync(ContestSubmission contestSubmission)
		{
			var problem = _context.Problems
				.Include(p => p.SourceWebsite)
				.Include(p => p.CodeForcesDetails)
				.Include(p => p.SimJudgeDetails)
				.SingleOrDefault(p => p.Id == contestSubmission.ProblemId);

			if (!ModelState.IsValid)
			{
				var languages = _context.Languages
					.Where(l => l.SourceWebsiteId == problem.SourceWebsiteId)
					.ToList();
				
				var submissionsViewModel = new ContestSubmissionViewModel
				{
					Languages = languages,
					ApplicationUserId = contestSubmission.ApplicationUserId,
					ProblemId = problem.Id,
					ProblemName = problem.Name,
					SourceProblemId = problem.SourceWebsite.Name + "-" + problem.SourceProblemId,
					ContestId = contestSubmission.ContestId
				};
				return View("Submit", submissionsViewModel);
			}
			
			contestSubmission.Code = Server.HtmlEncode(contestSubmission.Code);

			var language = _context.Languages
				.Where(l => l.SourceWebsiteId == problem.SourceWebsiteId)
				.SingleOrDefault(l => l.Id == contestSubmission.LanguageId);

			contestSubmission = await ContestSubmission.ProcessSubmissionAsync(contestSubmission, problem, language);

			_context.ContestSubmissions.Add(contestSubmission);

			var WrongAnswer = _context.ContestUserStatistics
				.Where(C => C.ContestId == contestSubmission.ContestId)
				.Where(c => c.ApplicationUserId == contestSubmission.ApplicationUserId)
				.SingleOrDefault(c => c.ProblemId == contestSubmission.ProblemId);

			// Count solved problems
			if (contestSubmission.Result == "Accepted")
			{
				var Solved = _context.ContestSubmissions
					.Where(c => c.ContestId == contestSubmission.ContestId)
					.Where(c => c.ApplicationUserId == contestSubmission.ApplicationUserId)
					.Where(c => c.ProblemId == contestSubmission.ProblemId)
					.FirstOrDefault(c => c.Result == "Accepted");
				var contestUser = _context.ContestUsers
					.Where(c => c.ContestId == contestSubmission.ContestId)
					.SingleOrDefault(s => s.ApplicationUserId == contestSubmission.ApplicationUserId);
				var contest = _context.Contests.SingleOrDefault(c => c.Id == contestSubmission.ContestId);


				if (Solved == null)
				{
					contestUser.SolvedProblems += 1;
					TimeSpan span = DateTime.Now.Subtract(contest.StartDate);
					contestUser.Penalty += (WrongAnswer.WrongAnswers * 20) + Convert.ToInt32(span.TotalMinutes);
				}
			}
			if (contestSubmission.Result != "Accepted" && contestSubmission.Result != "Compilation error" && contestSubmission.Result != "Duplicate Code on Source")
			{
				WrongAnswer.WrongAnswers += 1;
			}

			//Standing record
			var contestUserStatistics = _context.ContestUserStatistics
				.Where(c => c.ContestId == contestSubmission.ContestId)
				.Where(c => c.ApplicationUserId == contestSubmission.ApplicationUserId)
				.FirstOrDefault(c => c.ProblemId == contestSubmission.ProblemId);

			if (contestUserStatistics.ProblemStatus != "Accepted")
			{
				contestUserStatistics.ProblemStatus = contestSubmission.Result;
			}

			_context.SaveChanges();
			return RedirectToAction("ViewSubmissions", new { id = contestSubmission.ContestId });
		}
	}
}

Test/Views/ContestSubmissions/SubmissionDetails.cshtml
@model Test.Models.ContestSubmission
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<table id="Submissions" class="table table-bordered table-hover">
    <thead>
        <tr>
            <th>Sumbission Id</th>
            <th>User Name</th>
            <th>Problem Name</th>
            <th>Result</th>
            <th>Memory</th>
            <th>Time</th>
            <th>Language</th>
            <th>Submission Date</th>
        </tr>
    </thead>
    <tbody>
        @{var resultclass = Model.Result == "Accepted" ? "ac" : "notac"; }
        <tr>
            <td>@Model.Id</td>
            <td>@Model.ApplicationUser.UserName</td>
            <td>@Html.ActionLink(Model.Problem.Name, "ViewProblem", "ContestProblems", new { Model.ContestId, ProblemId = Model.Problem.Id}, null)</td>
            <td class="@resultclass">@Model.Result</td>
            <td>@Model.Memory</td>
            <td>@Model.Time</td>
            <td>@Model.Language.Name</td>
            <td>@Model.SubmissionTime</td>
        </tr>
    </tbody>
</table>
<pre>@Server.HtmlDecode(Model.Code)</pre>

Test/Views/ContestSubmissions/Submit.cshtml
@model Test.ViewModels.ContestSubmissionViewModel
@{
    ViewBag.Title = "Submit";
}
<h3>@Model.ProblemName</h3>
<br />
<div class="form-group">
    <div class="col-md-10">
        @Html.TextBoxFor(m => m.SourceProblemId, new { @class = "form-control ", @readonly = "readonly", @value = @Model.SourceProblemId })
    </div>
</div>
<br />
@using (Html.BeginForm("SaveSubmissionAsync", "ContestSubmissions", new { @class = "form-horizontal", role = "form" }))
{
    <div class="form-group">
        @Html.DropDownListFor(m => m.LanguageId, new SelectList(Model.Languages, "Id", "Name"), "Select Language", new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.LanguageId)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Code, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextAreaFor(m => m.Code, 30, 200, new { })
        </div>
        @Html.ValidationMessageFor(m => m.Code)
    </div>
    @Html.HiddenFor(m => m.ApplicationUserId)
    @Html.HiddenFor(m => m.ProblemId)
    @Html.HiddenFor(m => m.ContestId)
    @Html.AntiForgeryToken()
    <button class="btn btn-success" type="submit">Submit Problem</button>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Test/Views/ContestSubmissions/ViewSubmissions.cshtml
@model Test.ViewModels.ContestSubmissionsViewModel
@{
    ViewBag.Title = "ViewSubmissions";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Contest Submissions</h2>

<h4>Contest Name: @Model.ContestName</h4>

<table id="Submissions" class="table table-bordered table-hover">
    <thead>
        <tr>
            <th>Sumbission Id</th>
            <th>User Name</th>
            <th>Problem Name</th>
            <th>Result</th>
            <th>Memory</th>
            <th>Time</th>
            <th>Language</th>
            <th>Submission Date</th>
            <th>Code</th>
        </tr>
    </thead>
    <tbody>
        @if (!Model.ContestSubmissions.Any())
        {
            <tr>
                <td colspan="9" style="text-align:center">Contest Has No Submissions</td>
            </tr>
        }
        else
        {
            foreach (var submission in Model.ContestSubmissions)
            {
                var resultclass = submission.Result == "Accepted" ? "ac" : "notac";
                <tr>
                    <td>@submission.Id</td>
                    <td>@submission.ApplicationUser.UserName</td>
                    <td>@Html.ActionLink(submission.Problem.Name, "ViewProblem", "ContestProblems", new { submission.ContestId, ProblemId = submission.Problem.Id }, null)</td>
                    <td class="@resultclass">@submission.Result</td>
                    <td>@submission.Memory</td>
                    <td>@submission.Time</td>
                    <td>@submission.Language.Name</td>
                    <td>@submission.SubmissionTime</td>
                    <td>@Html.ActionLink("View Code", "SubmissionDetails", "ContestSubmissions", new { id = submission.Id, contestId = submission.ContestId }, null)</td>
                </tr>
            }
        }
    </tbody>
</table>