Test/Models/ProblemModels/Problem.cs
using System.ComponentModel.DataAnnotations;

namespace Test.Models
{
	public class Problem
	{
		public int Id { get; set; }

		public string Name { get; set; }

		public string SourceProblemId { get; set; }

		public SourceWebsite SourceWebsite { get; set; }
		
		public int SourceWebsiteId { get; set; }

		public ProblemDetails ProblemDetails { get; set; }

		public int ProblemDetailsId { get; set; }

		public CodeForcesDetails CodeForcesDetails { get; set; }

		public int? CodeForcesDetailsId { get; set; }

		public SimJudgeDetails SimJudgeDetails { get; set; }

		public int? SimJudgeDetailsId { get; set; }

		public const string LocalProblem = "SimJudge";

		public const int LocalProblemId = 1;

		public static string GetContestIdFromProblemId(string problem_id)
		{
			int contest_id_length = 0;
			for (int i = 0; i < problem_id.Length; ++i)
			{
				if (char.IsLetter(problem_id[i]))
				{
					contest_id_length = i;
					break;
				}
			}
			return problem_id.Substring(0, contest_id_length);
		}
	}
}

Test/ViewModels/ProblemViewModel.cs
using Test.Models;

namespace Test.ViewModels
{
	public class ProblemViewModel
	{
		public Problem Problem { get; set; }

		public int ContestId { get; set; }
	}
}

Test/Controllers/Apis/ProblemsController.cs
using AutoMapper;
using System;
using System.Data.Entity;
using System.Linq;
using System.Web.Http;
using System.Web.UI.WebControls;
using Test.Dtos;
using Test.Models;
namespace Test.Controllers.Apis
{

	public class ProblemsController : ApiController
	{
		private ApplicationDbContext _context;
		public ProblemsController()
		{
			_context = new ApplicationDbContext();
		}


		[AllowAnonymous]
		public IHttpActionResult GetProblem(string query = null)
		{
			var problemsQuery = _context.Problems
				.Include(m => m.SourceWebsite);

			if (!String.IsNullOrWhiteSpace(query))
				problemsQuery = problemsQuery.Where(c => c.Name.Contains(query));

			var problemDtos = problemsQuery
				.ToList()
				.Select(Mapper.Map<Problem, ProblemDto>);

			return Ok(problemDtos);
		}

		[AllowAnonymous]
		public IHttpActionResult GetProblem(int id)
		{
			var problem = _context.Problems.SingleOrDefault(p => p.Id == id);

			if (problem == null)
				return NotFound();

			return Ok(Mapper.Map<Problem, ProblemDto>(problem));
		}

		[HttpPost]
		public IHttpActionResult CreateProblem(ProblemDto problemDtos)
		{
			if (!ModelState.IsValid)
				return BadRequest();

			var problem = Mapper.Map<ProblemDto, Problem>(problemDtos);
			_context.Problems.Add(problem);
			_context.SaveChanges();

			return Created(new Uri(Request.RequestUri + "/" + problem.Id), problemDtos);
		}

		public IHttpActionResult UpdateProblem(int id, ProblemDto problemDtos)
		{
			if (!ModelState.IsValid)
				return BadRequest();
			var problemInDb = _context.Problems.SingleOrDefault(p => p.Id == id);

			if (problemInDb == null)
				return NotFound();
			Mapper.Map(problemDtos, problemInDb);
			_context.SaveChanges();
			return Ok();
		}

		[HttpDelete]
		public IHttpActionResult DeleteProblem(int id)
		{
			var problemInDb = _context.Problems.SingleOrDefault(p => p.Id == id);

			if (problemInDb == null)
				return NotFound();
			_context.Problems.Remove(problemInDb);
			_context.SaveChanges();
			return Ok();
		}
	}
}

Test/Controllers/Problems/ProblemsController.cs
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;
using Test.Models;

namespace Test.Controllers
{
	public class ProblemsController : Controller
	{
		private ApplicationDbContext _context;

		public ProblemsController()
		{
			_context = new ApplicationDbContext();
		}


		protected override void Dispose(bool disposing)
		{
			_context.Dispose();
		}

		[AllowAnonymous]
		public ActionResult Index()
		{
			return View();
		}

		[AllowAnonymous]
		[Route("Problems/{Id}")]
		public ActionResult ViewProblem(int Id)
		{
			var problem = _context.Problems
				.Include(p => p.SourceWebsite)
				.Include(p => p.ProblemDetails)
				.Include(p => p.SimJudgeDetails)
				.Include(p => p.CodeForcesDetails)
				.SingleOrDefault(p => p.Id == Id);

			if (problem == null)
				return HttpNotFound();

			var viewName = problem.SourceWebsite.Name + "Problem";
			return View(viewName, problem);
		}

		[Authorize(Roles = RoleName.Admin)]
		[Route("Problems/CreateLocalProblem")]
		public ActionResult CreateLocalProblem()
		{
			var problem = new Problem();
			return View("SimJudgeProblemForm", problem);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		[Route("Problems/SaveLocalProblem")]
		public ActionResult SaveLocalProblem(Problem Problem)
		{
			if (!ModelState.IsValid)
			{
				return View("SimJudgeProblemForm", Problem);
			}
			
			Problem.SimJudgeDetails.TestCaseInput = Server.HtmlEncode(Problem.SimJudgeDetails.TestCaseInput);
			Problem.SimJudgeDetails.TestCaseOutput = Server.HtmlEncode(Problem.SimJudgeDetails.TestCaseOutput);

			Problem.SourceWebsiteId = Problem.LocalProblemId;

			_context.Problems.Add(Problem);
			_context.SaveChanges();

			Problem.SourceProblemId = Problem.Id.ToString();
			_context.SaveChanges();

			return RedirectToAction("ViewProblem", new { Id = Problem.Id });
		}
	}
}

Test/Controllers/Problems/SubmissionsController.cs
using Microsoft.AspNet.Identity;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using Test.Models;
using Test.ViewModels;

namespace Test.Controllers
{
	public class SubmissionsController : Controller
	{
		private ApplicationDbContext _context;

		public SubmissionsController()
		{
			_context = new ApplicationDbContext();
		}


		protected override void Dispose(bool disposing)
		{
			_context.Dispose();
		}

		[AllowAnonymous]
		public ActionResult Index()
		{
			var submissions = _context.Submissions
				.Include(s => s.Problem)
				.Include(s => s.ApplicationUser)
				.Include(s => s.Language)
				.ToList();

			return View(submissions);
		}

		public ActionResult UserSubmissions()
		{
			var userId = User.Identity.GetUserId();
			var submissions = _context.Submissions
				.Where(s => s.ApplicationUserId == userId)
				.Include(s => s.Problem)
				.Include(s => s.ApplicationUser)
				.Include(s => s.Language)
				.ToList();

			return View("Index", submissions);
		}

		public ActionResult Details(int id)
		{
			var submission = _context.Submissions
				.Include(s => s.Problem)
				.Include(s => s.ApplicationUser)
				.Include(s => s.Language)
				.SingleOrDefault(s => s.Id == id);

			if (submission == null)
				return HttpNotFound();

			return View(submission);
		}

		[Route("Submissions/Submit/{Id}")]
		public ActionResult Submit(int id)
		{
			var problem = _context.Problems
				.Include(p => p.SourceWebsite)
				.Include(p => p.CodeForcesDetails)
				.Include(p => p.SimJudgeDetails)
				.SingleOrDefault(p => p.Id == id);

			if (problem == null)
				return HttpNotFound();

			var userId = User.Identity.GetUserId();

			var languages = _context.Languages
				.Where(l => l.SourceWebsiteId == problem.SourceWebsiteId)
				.ToList();

			var submissionsViewModel = new SubmissionsViewModel
			{
				Languages = languages,
				ApplicationUserId = userId,
				ProblemId = problem.Id,
				ProblemName = problem.Name,
				SourceProblemId = problem.SourceWebsite.Name + "-" + problem.SourceProblemId
			};
			return View(submissionsViewModel);
		}

		[ValidateAntiForgeryToken]
		[HttpPost]
		public async Task<ActionResult> SaveProblemSubmissionAsync(Submission submission)
		{
			var problem = _context.Problems
				.Include(p => p.SourceWebsite)
				.Include(p => p.CodeForcesDetails)
				.Include(p => p.SimJudgeDetails)
				.SingleOrDefault(p => p.Id == submission.ProblemId);

			if (!ModelState.IsValid)
			{
				var languages = _context.Languages
					.Where(l => l.SourceWebsiteId == problem.SourceWebsiteId)
					.ToList();

				var submissionsViewModel = new SubmissionsViewModel
				{
					Languages = languages,
					ApplicationUserId = submission.ApplicationUserId,
					ProblemId = problem.Id,
					ProblemName = problem.Name,
					SourceProblemId = problem.SourceWebsite.Name + "-" + problem.SourceProblemId
				};
				return View(submissionsViewModel);
			}

			submission.Code = Server.HtmlEncode(submission.Code);
			
			var language = _context.Languages
				.Where(l => l.SourceWebsiteId == problem.SourceWebsiteId)
				.SingleOrDefault(l => l.Id == submission.LanguageId);

			submission = await Submission.ProcessSubmissionAsync(submission, problem, language);
			_context.Submissions.Add(submission);

			_context.SaveChanges();
			return RedirectToAction("UserSubmissions");
		}
	}
}

Test/Views/Problems/CodeForcesProblem.cshtml
@model Test.Models.Problem
@{
    ViewBag.Title = "Problem";
}

<script>
    MathJax = {
        tex: {
            inlineMath: [['$$$', '$$$'], ['\\(', '\\)']]
        }
    };
</script>
<script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js"></script>

<h2>@Model.Name</h2>
<h4 style="flex-direction: row">Problem Id: @Model.SourceWebsite.Name-@Model.SourceProblemId</h4>
<h4>Contest Name: @Model.CodeForcesDetails.ContestSource</h4>
<h4><a href="@Model.CodeForcesDetails.SourceUrl">Problem Link</a></h4>
<div style="display: flex;">

    <div class="jumbotron " style="padding: 10px; margin: 20px;width:80%">

        <div style="margin: 15px;">
            <h2 style="text-align: center">Description</h2>
            <div class="jumbotron" style="padding: 5px;">
                @Html.Raw(Model.ProblemDetails.Description)
            </div>
        </div>

        <div style="margin: 15px;">
            <h2 style="text-align: center">Input</h2>
            <div class="jumbotron" style="padding: 5px;">
                @Html.Raw(Model.ProblemDetails.Input)
            </div>
        </div>

        <div style="margin: 15px;">
            <h2 style="text-align: center">Output</h2>
            <div class="jumbotron" style="padding: 5px;">
                @Html.Raw(Model.ProblemDetails.Output)
            </div>
        </div>

        <div style="margin: 15px;">
            <h2 style="text-align: center">Examples</h2>
            <div class="jumbotron" style="padding: 5px;">
                @Html.Raw(Model.CodeForcesDetails.Examples)
            </div>
        </div>

        <div style="margin: 15px;">
            <h2 style="text-align: center">Notes</h2>
            <div class="jumbotron" style="padding: 5px;">
                @Html.Raw(Model.ProblemDetails.Notes)
            </div>
        </div>

    </div>

    <div style="padding: 5px;margin: 20px">

        <div style="margin: 15px;">

            <div class="jumbotron" style="padding: 5px;">
                <h5 style="text-align: center">Time Limit:</h5>
                <p style="text-align: center"> @Model.ProblemDetails.TimeLimit</p>
            </div>

            <div class="jumbotron" style="padding: 5px;">
                <h5 style="text-align: center">Memory Limit:</h5>
                <p style="text-align: center"> @Model.ProblemDetails.MemoryLimit</p>
            </div>

            <div class="jumbotron" style="padding: 10px;">
                <h5 style="text-align: center">Input File:</h5>
                <p style="text-align: center"> @Model.CodeForcesDetails.InputFile</p>
            </div>

            <div class="jumbotron" style="padding: 10px;">
                <h5 style="text-align: center">Output File:</h5>
                <p style="text-align: center"> @Model.CodeForcesDetails.OutputFile</p>
            </div>

            <div class="jumbotron" style="padding: 10px;">
                <h5 style="text-align: center">Editorial:</h5>
                @Html.Raw(Model.CodeForcesDetails.Editorial)
            </div>

            <div class="jumbotron" style="padding: 10px;">
                <h5 style="text-align: center">Problem Tags:</h5>
                <p style="text-align: center"> @Model.CodeForcesDetails.Tags</p>
            </div>

        </div>
    </div>
</div>
@Html.ActionLink("Submit", "Submit", "Submissions", new { Model.Id }, new { @class = "btn btn-success" })

Test/Views/Problems/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Problems</h2>
<table id="problems" class="table table-bordered table-hover">
    <thead>
        <tr>
            <th>Problem Name</th>
            <th>Source</th>
        </tr>
    </thead>
    <tbody>
    </tbody>
</table>

@section scripts
{
    <script>
        $(document).ready(function () {
            $("#problems").DataTable({
                ajax: {
                    url: "/api/problems",
                    dataSrc: ""
                },
                columns: [
                    {
                        data: "name",
                        render: function (data, type, problem) {
                            return "<a href='/Problems/" + problem.id + "'>" + problem.name + "</a>";
                        }
                    },
                    {
                        data: "sourceWebsite.name"
                    }
                ]
            });

        });
    </script>
}

Test/Views/Problems/SimJudgeProblem.cshtml
@model Test.Models.Problem
@{
    ViewBag.Title = "Problem";
}

<script>
    MathJax = {
        tex: {
            inlineMath: [['$$$', '$$$'], ['\\(', '\\)']]
        }
    };
</script>
<script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js"></script>

<h2>@Model.Name</h2>
<h4 style="flex-direction: row">Problem Id: @Model.SourceWebsite.Name-@Model.SourceProblemId</h4>
<div style="display: flex;">

    <div class="jumbotron " style="padding: 10px; margin: 20px;width:80%">
        <div style="margin: 15px;">
            <h2 style="text-align: center">Description</h2>
            <div class="jumbotron" style="padding: 5px;">
                @Model.ProblemDetails.Description
            </div>
        </div>

        <div style="margin: 15px;">
            <h2 style="text-align: center">Input</h2>
            <div class="jumbotron" style="padding: 5px;">
                @Model.ProblemDetails.Input
            </div>
        </div>

        <div style="margin: 15px;">
            <h2 style="text-align: center">Output</h2>
            <div class="jumbotron" style="padding: 5px;">
                @Model.ProblemDetails.Output
            </div>
        </div>

        <div style="margin: 15px;">
            <h2 style="text-align: center">Examples</h2>
            <p>Input:</p>
            <div class="jumbotron" style="padding: 5px;">
                @Server.HtmlDecode(Model.SimJudgeDetails.TestCaseInput)
            </div>
            <p>Output:</p>
            <div class="jumbotron" style="padding: 5px;">
                @Server.HtmlDecode(Model.SimJudgeDetails.TestCaseOutput)
            </div>
        </div>

        <div style="margin: 15px;">
            <h2 style="text-align: center">Notes</h2>
            <div class="jumbotron" style="padding: 5px;">
                @Model.ProblemDetails.Notes
            </div>
        </div>
    </div>

    <div style="padding: 5px;margin: 20px">

        <div style="margin: 15px;">

            <div class="jumbotron" style="padding: 5px;">
                <h5 style="text-align: center">Time Limit:</h5>
                <p style="text-align: center"> @Model.ProblemDetails.TimeLimit</p>
            </div>

            <div class="jumbotron" style="padding: 5px;">
                <h5 style="text-align: center">Memory Limit:</h5>
                <p style="text-align: center"> @Model.ProblemDetails.MemoryLimit</p>
            </div>
        </div>
    </div>
</div>
@Html.ActionLink("Submit", "Submit", "Submissions", new { Model.Id }, new { @class = "btn btn-success" })

Test/Views/Problems/SimJudgeProblemForm.cshtml
@model Test.Models.Problem
@{
    ViewBag.Title = "SimJudge Problem Form";
}

<h2>SimJudge Problem Form</h2>

@Html.ValidationSummary()
@using (Html.BeginForm("SaveLocalProblem", "Problems", new { @class = "form-horizontal" }))
{
    <div class="form-group">
        @Html.LabelFor(m => m.Name)
        @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Name)
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.ProblemDetails.Description)
        @Html.TextBoxFor(m => m.ProblemDetails.Description, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.ProblemDetails.Description)
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.ProblemDetails.Input)
        @Html.TextBoxFor(m => m.ProblemDetails.Input, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.ProblemDetails.Input)
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.ProblemDetails.Output)
        @Html.TextBoxFor(m => m.ProblemDetails.Output, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.ProblemDetails.Output)
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.ProblemDetails.Notes)
        @Html.TextBoxFor(m => m.ProblemDetails.Notes, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.ProblemDetails.Notes)
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.SimJudgeDetails.TestCaseInput)
        @Html.TextBoxFor(m => m.SimJudgeDetails.TestCaseInput, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.SimJudgeDetails.TestCaseInput)
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.SimJudgeDetails.TestCaseOutput)
        @Html.TextBoxFor(m => m.SimJudgeDetails.TestCaseOutput, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.SimJudgeDetails.TestCaseOutput)
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.ProblemDetails.TimeLimit)
        @Html.TextBoxFor(m => m.ProblemDetails.TimeLimit, new { @class = "form-control", @Value = "1" })
        @Html.ValidationMessageFor(m => m.ProblemDetails.TimeLimit)
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.ProblemDetails.MemoryLimit)
        @Html.TextBoxFor(m => m.ProblemDetails.MemoryLimit, new { @class = "form-control", @Value = "256" })
        @Html.ValidationMessageFor(m => m.ProblemDetails.MemoryLimit)
    </div>

    @Html.AntiForgeryToken()
    <button class="btn btn-success" type="submit">Submit Problem</button>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}